### ISSUE TITLE
Ogarnąć błąd 422 podczas logowania

### ISSUE THREAD

**Issue by nieznamjs** [purbanski-deftcode/learning-hub#40]
Jeśli podczas logowania nie podamy e-maila, tylko jakiś inny string to dostajemy errora 422 i nie pokazuje errora pod formularzem.

Na froncie nie robić po prostu requestu jeśli formularz jest invalid.

**Comment by purbanski-deftcode** [comment]
Błąd jest tylko na froncie. Backend ładnie zwraca 422 jak wspomniałeś plus odpowiednie info (`Validation error` i odpowiedni message).
