### ISSUE TITLE
Dodać widoki dodawania grup

### ISSUE THREAD

**Issue by purbanski-deftcode** [purbanski-deftcode/learning-hub#57]
Zrobić je praktycznie na tej samej zasadzie co ścieżki z jedną różnicą: obok pola nazwy powinien być select z wyszukiwarką (może coś w tym stylu https://github.com/OasisDigital/angular-material-search-select).
W przypadku sekcji w select powinniśmy wybierać do jakiej ścieżki sekcja należy (może należeć do więcej niż jednej, np. vanilla js do frontu i do backendu w nodejs). Natomiast w przypadku grupy wybieramy w select do jakiej sekcji dana grupa należy.

Sekcja może należeć do więcej niż jednej ścieżki i wtedy request body ma tablice `paths` z idkami ścieżek.
Grupa może należeć tylko do jednej sekcji i wtedy pod polem `section` ma odpowiednie id sekcji.

EDIT: Sekcje przeniesione do #68

**Comment by nieznamjs** [comment]
Rozdzieliłbym tego taska na dwa osobne, a jak już to połączył #58 z grupami.

**Comment by purbanski-deftcode** [comment]
@nieznamjs a to sobie podziel
